### ISSUE TITLE
Add integration with Google Music, Spotify, etc

### ISSUE THREAD

**Issue by curpeng** [spywhere/vscode-now-playing#1]
Will be great to have integration with cloud music services. 

You can use https://github.com/simon-weber/gmusicapi as the example for integration with google music.

**Comment by spywhere** [comment]
Thanks for the suggestion. However due to the complexity and availability of the service, this would take quite a while. I will leave this issue open as it might be integrated in the future.

**Comment by spywhere** [comment]
Spotify now supported. Better late than never. 😜

Just a reference for future request, please open up a new ticket per integration since one might get implemented before another.
