### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by rmaes4** [spywhere/vscode-now-playing#2]
I can't see anything in my status bar.

**Comment by spywhere** [comment]
First of, what is your operating system and its version? What music player are you using? Which version of VSCode you are using (assumed you already install the latest version of the extension)?

**Comment by rmaes4** [comment]
Mac OS X High Sierra 10.13.4
iTunes
VS Code 1.21.0

**Comment by spywhere** [comment]
The issue came from the script used by the extension in which applications cannot be found. So in the mean time, you could install the missing players in order to use the extension as a workaround. I'll update the issue once I got the fix ready.

**Comment by spywhere** [comment]
The issue has been fixed in v0.1.5
