### ISSUE TITLE
Player Priority

### ISSUE THREAD

**Issue by computamike** [spywhere/vscode-now-playing#4]
![image](https://user-images.githubusercontent.com/464876/48267319-ea454380-e429-11e8-8639-1e95fb0d0095.png)

**Comment by computamike** [comment]
identified the issue.  I had quicktime and Itunes open.  In this instance I had recorded a screen recording. Interestingly in that scenario mac seems to remember which application had the media keys pressed last.  Maybe the system should find the media systems executing and pick which ever one the user prioritises (so - in my example I'd get the extension to work with iTunes, rather than quicktime.

**Comment by spywhere** [comment]
Nice finding. I didn't think about the player ordering at first, but now could be the time to do it. I'll keep you dated once there is some progress on this one.

**Comment by spywhere** [comment]
Implemented in v0.3.0
