### ISSUE TITLE
Not functioning correctly when using SSH Remote Development extension

### ISSUE THREAD

**Issue by DerpyChap** [spywhere/vscode-now-playing#5]
When using the [SSH Remote Development](https://code.visualstudio.com/docs/remote/ssh) extension on VSCode Insiders the extension can only run on the target server. 
![image](https://user-images.githubusercontent.com/15108194/57785036-d821c600-7728-11e9-8f4c-f75009529471.png)

This basically means that, while using SSH Remote Development, the extension can no longer see what music I'm playing as it can't run locally.

They have a page for writing extensions with remote development in mind [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions), but it basically requires that the extension runs as a "Theme/UI" extension, and I'm not sure what limitations that could have.

**Comment by spywhere** [comment]
Thanks for the issue, will keep you dated on the progress. Might take some time though.

**Comment by spywhere** [comment]
For workaround during the development, please checkout [this link](https://code.visualstudio.com/api/advanced-topics/remote-extensions#common-problems) for how to setup `remote.extensionKind` settings to override the execution location.

**Comment by spywhere** [comment]
Implemented in v0.2.3
